version: 2

project_name: lazywork

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/miltonparedes/lazywork/cmd.Version={{.Version}}
      - -X github.com/miltonparedes/lazywork/cmd.Commit={{.Commit}}
      - -X github.com/miltonparedes/lazywork/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

brews:
  - name: lazywork
    repository:
      owner: miltonparedes
      name: homebrew-tap
    homepage: https://github.com/miltonparedes/lazywork
    description: AI-powered Git workflow automation
    license: MIT
    install: |
      bin.install "lazywork"
    test: |
      system "#{bin}/lazywork", "version"
