version: 2

project_name: lazywork

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/miltonparedes/lazywork/cmd.Version={{.Version}}
      - -X github.com/miltonparedes/lazywork/cmd.Commit={{.Commit}}
      - -X github.com/miltonparedes/lazywork/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  mode: keep-existing

changelog:
  # Disabled - using GitHub's "Generate release notes" instead
  disable: true
